version: '3.8'

services: 
    database:
        build: ./app/database
        ports:
            - 5433:5432
        env_file:
            - ./app/database/.env
        container_name: database
    backend:
        build: ./app/backend
        ports:
            - 8081:8000
        env_file: 
            - ./app/backend/.env
        container_name: backend
        depends_on:
            - database
