version: '3.8'

services: 
    database:
        build: ./app/SmartHome-Database
        volumes: 
            - database:/var/lib/postgresql/11/main
            - ~/SmartHome/database/backups:/backups
        ports:
            - 5432:5432
        env_file:
            - ./app/SmartHome-Database/.env
        container_name: database
    backend:
        build: ./app/SmartHome-Backend
        ports:
            - 8080:8000
        env_file: 
            - ./app/SmartHome-Backend/.env
        container_name: backend
        depends_on:
            - database
    tauron:
        build: ./app/SmartHome-TauronEMeter
        volumes: 
            - apps:/usr/src/app
        env_file:
            - ./app/SmartHome-TauronEMeter/.env            
        container_name: tauron
        depends_on:
            - backend
        tty: true
    solarman:
        build: ./app/SmartHome-SolarMan
        env_file:
            - ./app/SmartHome-SolarMan/.env
        container_name: solarman
        depends_on:
            - backend
        tty: true
volumes: 
    database: